name = "ggbomb"
main = "src/worker.js"
compatibility_date = "2024-11-01"
workers_dev = true

[durable_objects]
bindings = [
  { name = "SEARCH_DO", class_name = "SearchShield" }
]

[[migrations]]
tag = "v1-sqlite"
new_sqlite_classes = ["SearchShield"]
